/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import Business.Photo;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author luoqi
 */
public class CreatePanel extends javax.swing.JPanel {
    
    private Person person;
    private Photo photo;

    /**
     * Creates new form CreatePanel
     */
    public CreatePanel(Person person) {
        initComponents();
        this.person = person;
        this.photo = person.getFacePhoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        birthdayTxt = new javax.swing.JTextField();
        teleNumTxt = new javax.swing.JTextField();
        FAXNumTxt = new javax.swing.JTextField();
        emailTxt = new javax.swing.JTextField();
        SSNTxt = new javax.swing.JTextField();
        medicalNumTxt = new javax.swing.JTextField();
        healthNumTxt = new javax.swing.JTextField();
        bankNumTxt = new javax.swing.JTextField();
        licenseNumTxt = new javax.swing.JTextField();
        vehicleNumTxt = new javax.swing.JTextField();
        deviceNumTxt = new javax.swing.JTextField();
        linkedInNumTxt = new javax.swing.JTextField();
        interProtocalNumTxt = new javax.swing.JTextField();
        biometricIdentTxt = new javax.swing.JTextField();
        otherTxt = new javax.swing.JTextField();
        uploadPictureBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("Create Person");

        jLabel2.setText("Name :");

        jLabel3.setText("Address :");

        jLabel4.setText("Birthday :");

        jLabel5.setText("Telephone Number");

        jLabel6.setText("FAX Number :");

        jLabel7.setText("E-mail Address :");

        jLabel8.setText("Social Security Number :");

        jLabel9.setText("Medical Record Number :");

        jLabel10.setText("Health Plan Number :");

        jLabel11.setText("Bank Account Number :");

        jLabel12.setText("License Number :");

        jLabel13.setText("Vehicle Identifier Number :");

        jLabel14.setText("Face Photo :");

        jLabel15.setText("Device Number :");

        jLabel16.setText("Internet Protocol Address :");

        jLabel17.setText("LinkedIn :");

        jLabel18.setText("Biometric Identifier :");

        jLabel19.setText("Other :");

        nameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtActionPerformed(evt);
            }
        });

        birthdayTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birthdayTxtActionPerformed(evt);
            }
        });

        uploadPictureBtn.setText("upload picture");
        uploadPictureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPictureBtnActionPerformed(evt);
            }
        });

        createBtn.setText("Create");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(createBtn)
                .addGap(400, 400, 400))
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(addressTxt)
                            .addComponent(birthdayTxt)
                            .addComponent(teleNumTxt)
                            .addComponent(FAXNumTxt)
                            .addComponent(emailTxt)
                            .addComponent(SSNTxt)
                            .addComponent(medicalNumTxt)
                            .addComponent(healthNumTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel14)
                            .addComponent(jLabel19))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bankNumTxt)
                            .addComponent(licenseNumTxt)
                            .addComponent(vehicleNumTxt)
                            .addComponent(deviceNumTxt)
                            .addComponent(linkedInNumTxt)
                            .addComponent(interProtocalNumTxt)
                            .addComponent(biometricIdentTxt)
                            .addComponent(otherTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(uploadPictureBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(addressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(birthdayTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(teleNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(FAXNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(emailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(SSNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(medicalNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(healthNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(bankNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(licenseNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(vehicleNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(deviceNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(linkedInNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(interProtocalNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(biometricIdentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(otherTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(uploadPictureBtn))))
                .addGap(37, 37, 37)
                .addComponent(createBtn)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtActionPerformed

    private void birthdayTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birthdayTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birthdayTxtActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
       
        person.setName(nameTxt.getText());
        person.setAddress(addressTxt.getText());        
        person.setBirthday(birthdayTxt.getText());
        person.setTelephoneNumber(Long.parseLong(teleNumTxt.getText())); 
        person.setFAXnumber(Long.parseLong(FAXNumTxt.getText()));
        person.setAddress(emailTxt.getText());
        person.setSocialSecurityNumber(SSNTxt.getText());
        person.setMedicalRecordNumber(medicalNumTxt.getText());
        person.setHealthPlanNumber(healthNumTxt.getText());
        person.setBankAccountNumber(bankNumTxt.getText());
        person.setLicenseNumber(licenseNumTxt.getText());
        person.setVehicleIdentifierNumber(vehicleNumTxt.getText());
        person.setDeviceNumber(deviceNumTxt.getText());
        person.setLinkedIn(linkedInNumTxt.getText());
        person.setInternetProtocolAddress(interProtocalNumTxt.getText());
        person.setBiometricIdentifier(biometricIdentTxt.getText());
        person.setOther(otherTxt.getText());       
        JOptionPane.showMessageDialog(null, "Create product successfully");

        
        
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void uploadPictureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadPictureBtnActionPerformed
        // TODO add your handling code here:
        
        //打开文件选择器
        JFileChooser chooser = new JFileChooser();
        chooser.setMultiSelectionEnabled(true);//将chooser初始化，设置可以选中多个问题
      
        //设置可以选择的文件类型
        //FileNameExtensionFilter filter = new FileNameExtensionFilter(".jpg",".jepg",".png");
        //chooser.setFileFilter(filter);
	
        
        //如果选中某个文件则将文件选择并存到selectfiles中
	File[] selectfiles = chooser.getSelectedFiles();
	if (selectfiles == null || selectfiles.length == 0) {
            return;
        }
            
        FileInputStream input = null;
        FileOutputStream out = null;
        
        //设置存到图片的路径
        String path = photo.getLoadPath();
	try {
            for (File f : selectfiles) {
                //通过文件选择器对象拿到选择的文件.拿到该文件的绝对路径
		photo.setAbsolutePath(chooser.getSelectedFile().getAbsolutePath());

		input = new FileInputStream(f);
		byte[] buffer = new byte[1024];
		File selectFile = new File(path, f.getName());
		out = new FileOutputStream(selectFile);
		int len = 0;
                
                //开始写文件
		while ((len = input.read(buffer)) != -1) {
                    out.write(buffer, 0, len);
		}
                //每次都重新new input 和 out
		out.close();
		input.close();
            }  
		JOptionPane.showMessageDialog(null, "上传成功！", "提示",JOptionPane.INFORMATION_MESSAGE);
        } catch (FileNotFoundException e1) {
            JOptionPane.showMessageDialog(null, "上传失败！", "提示",JOptionPane.ERROR_MESSAGE);
            e1.printStackTrace();
        } catch (IOException e1) {
            JOptionPane.showMessageDialog(null, "上传失败！", "提示",JOptionPane.ERROR_MESSAGE);
            e1.printStackTrace();
        }
        
        
        //int returnVal = chooser.showOpenDialog(uploadPictureBtn);
	//if (returnVal == JFileChooser.APPROVE_OPTION) { 

               
    }//GEN-LAST:event_uploadPictureBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FAXNumTxt;
    private javax.swing.JTextField SSNTxt;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField bankNumTxt;
    private javax.swing.JTextField biometricIdentTxt;
    private javax.swing.JTextField birthdayTxt;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField deviceNumTxt;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField healthNumTxt;
    private javax.swing.JTextField interProtocalNumTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField licenseNumTxt;
    private javax.swing.JTextField linkedInNumTxt;
    private javax.swing.JTextField medicalNumTxt;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField otherTxt;
    private javax.swing.JTextField teleNumTxt;
    private javax.swing.JButton uploadPictureBtn;
    private javax.swing.JTextField vehicleNumTxt;
    // End of variables declaration//GEN-END:variables
}
