/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Car;
import Business.CarDirectory;
import java.awt.CardLayout;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author luoqi
 */
public class ViewDetailPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Car car;
    private CarDirectory carDirectory;
    final private String str = "((\\d{2}(([02468][048])|([13579][26]))[\\-]((((0?[13578])|(1[02]))[\\-]((0?[1-9])|([1-2][0-9])|(3[01])))|(((0?[469])|(11))[\\-]((0?[1-9])|([1-2][0-9])|(30)))|(0?2[\\-]((0?[1-9])|([1-2][0-9])))))|(\\d{2}(([02468][1235679])|([13579][01345789]))[\\-]((((0?[13578])|(1[02]))[\\-]((0?[1-9])|([1-2][0-9])|(3[01])))|(((0?[469])|(11))[\\-]((0?[1-9])|([1-2][0-9])|(30)))|(0?2[\\-]((0?[1-9])|(1[0-9])|(2[0-8]))))))";


    /**
     * Creates new form ViewDetailPanel
     */
    public ViewDetailPanel() {
        initComponents();
    }
    
    ViewDetailPanel(JPanel userProcessContainer, Car car, CarDirectory carDirectory) {
        initComponents();    
        this.userProcessContainer = userProcessContainer;
        this.car = car;
        this.carDirectory = carDirectory;
        populateCarDetail();
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
    }
    
    private void populateCarDetail(){
        certificateTxt.setText(dateToStr(car.getCertificate()));
        cityTxt.setText(car.getCity());
        madeYearTxt.setText(String.valueOf(car.getMakeYear()));
        manufacturerTxt.setText(car.getManufacturer());
        modelNumTxt.setText(car.getModelNumber());
        seatTxt.setText(String.valueOf(car.getSeats()));
        serialNumTxt.setText(car.getSerialNumber());
        
        if(car.isStatus()){
            availableCheckBox.setSelected(true);
            notAvailableCheckBox.setSelected(false);
            
        }else {
            availableCheckBox.setSelected(false);
            notAvailableCheckBox.setSelected(true);
        }
              

    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cityTxt = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        madeYearTxt = new javax.swing.JTextField();
        serialNumTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        manufacturerTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modelNumTxt = new javax.swing.JTextField();
        certificateTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        seatTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        availableCheckBox = new javax.swing.JCheckBox();
        notAvailableCheckBox = new javax.swing.JCheckBox();

        cityTxt.setEnabled(false);

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Serial Number :");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Seat :");

        madeYearTxt.setEnabled(false);

        serialNumTxt.setEnabled(false);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("City :");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Manufacturer :");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Made Year :");

        manufacturerTxt.setEnabled(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Model Number :");

        modelNumTxt.setEnabled(false);

        certificateTxt.setEnabled(false);
        certificateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateTxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Car");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Certificate :");

        seatTxt.setEnabled(false);

        jLabel9.setText("Status :");

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        availableCheckBox.setText("Available");
        availableCheckBox.setEnabled(false);

        notAvailableCheckBox.setText("Not Available");
        notAvailableCheckBox.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(100, 100, 100)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(manufacturerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(serialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(modelNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(seatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(certificateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(madeYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9))
                                .addGap(146, 146, 146)
                                .addComponent(availableCheckBox)))))
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notAvailableCheckBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(saveBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateBtn)))
                .addGap(164, 164, 164))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(backBtn))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(serialNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(manufacturerTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(modelNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(certificateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(seatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(madeYearTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(availableCheckBox)
                    .addComponent(notAvailableCheckBox))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(updateBtn))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void certificateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificateTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
        certificateTxt.setEnabled(true);
        cityTxt.setEnabled(true);
        madeYearTxt.setEnabled(true);
        manufacturerTxt.setEnabled(true);
        modelNumTxt.setEnabled(true);
        seatTxt.setEnabled(true);
        serialNumTxt.setEnabled(true);
        //statusTxt.setEnabled(true);
        
        availableCheckBox.setEnabled(true);
        notAvailableCheckBox.setEnabled(true);
        
        
        
        saveBtn.setEnabled(true);
        updateBtn.setEnabled(false );
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        
        /*
        if(carDirectory.searchSerialNumber(serialNumTxt.getText()) != null){
            JOptionPane.showMessageDialog(null, "dont enter the same infomation","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
*/

        
        if((availableCheckBox.isSelected() == true && notAvailableCheckBox.isSelected()  == true) || (availableCheckBox.isSelected() == false && notAvailableCheckBox.isSelected()  == false)){
            JOptionPane.showMessageDialog(null, "Please select status","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if( serialNumTxt.getText().matches(".*[a-zA-Z]+.*") && serialNumTxt.getText().length() != 0
                &&  manufacturerTxt.getText().matches(".*[a-zA-Z]+.*") && manufacturerTxt.getText().length() != 0
                && modelNumTxt.getText().matches(".*[a-zA-Z]+.*") && modelNumTxt.getText().length() != 0
                && cityTxt.getText().matches(".*[a-zA-Z]+.*") && cityTxt.getText().length() != 0
                && madeYearTxt.getText().matches("^\\+{0,1}[1-9]\\d*") && madeYearTxt.getText().length() != 0
                && seatTxt.getText().matches("^\\+{0,1}[1-9]\\d*") && seatTxt.getText().length() != 0
                && certificateTxt.getText().matches(str) && certificateTxt.getText().length() != 0
                ){
            
            
            try{
            
            String serialNumber = serialNumTxt.getText();
            String manufacturer = manufacturerTxt.getText();
            String modelNumber = modelNumTxt.getText();
            String city = cityTxt.getText();
            int makeYear = Integer.parseInt(madeYearTxt.getText());
            int seats = Integer.parseInt(seatTxt.getText());            
            Date certificate = cerDate(certificateTxt.getText());
            boolean status;
            if(availableCheckBox.isSelected()){
                status = true;
            }else{
                
                status = false;
            }

            
            
        
            //Car car = carDirectory.addCar();
            
            car.setCertificate(certificate);
            car.setCity(city);
            car.setMakeYear(makeYear);
            car.setManufacturer(manufacturer);
            car.setModelNumber(modelNumber);
            car.setSeats(seats);
            car.setSerialNumber(serialNumber);
            
            //todo 设置两个符号
            car.setStatus(status);//每一辆车在刚开始注册的时候自动为avaliable


        
            //JOptionPane.showMessageDialog(null, "Account add Successfully");

            
            }catch(ParseException e){
                JOptionPane.showMessageDialog(null, "Please enter right time format", "Warning",JOptionPane.WARNING_MESSAGE);
                e.printStackTrace();
            }

        
            
        } else{
            
            JOptionPane.showMessageDialog(null, "Please enter right information","Warning",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true );
        
        JOptionPane.showMessageDialog(null, "Car Information updates successfully!"); 
        
    }//GEN-LAST:event_saveBtnActionPerformed

    private String dateToStr(Date dateDate) {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        String dateString = formatter.format(dateDate);
        return dateString;
    }
    private Date cerDate(String cerdate) throws ParseException{
        return parseCertificateDate(cerdate);
    }
        
    private Date parseCertificateDate(String cerdate) throws ParseException{
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");        
        Date certificateDate = simpleDateFormat.parse(cerdate);
        return certificateDate;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox availableCheckBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField certificateTxt;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField madeYearTxt;
    private javax.swing.JTextField manufacturerTxt;
    private javax.swing.JTextField modelNumTxt;
    private javax.swing.JCheckBox notAvailableCheckBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField seatTxt;
    private javax.swing.JTextField serialNumTxt;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
